# Generated by Django 3.2 on 2021-04-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
