# Generated by Django 3.2 on 2021-04-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_app', '0002_docfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocFile',
        ),
    ]
