# Generated by Django 3.2 on 2021-04-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_app', '0005_alter_document_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date_expired',
        ),
    ]
